---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: <%= ENV["machine_port"] %>
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.6
    attributes:
      orchestrator:
        package:
          version: 2.1.5-1
          url: 'https://github.com/kplimack/orchestrator-rpm/raw/master/orchestrator-2.1.5-1.x86_64.rpm'
          checksum: 392a2d6b3d5cea85053dfad3b6c2dceae838674d56f267046c854e4d1ceee2a3
  - name: centos-7.2
  - name: debian-8.9
    attributes:
      orchestrator:
        package:
          version: ~

suites:
  - name: default
    run_list:
    - recipe[orchestrator::default]
